### ISSUE TITLE
React: `variant` prop should be optional

### ISSUE THREAD

**Issue by junwen-k** [0xa3k5/web3icons#15]
### Issue

Typescript complains if `variant` prop is not specified when using Icons from React package.
It looks like `mono` should be the default value if not specified.

```ts
Property 'variant' is missing in type '{ className: string; }' but required in type 'Omit<IconComponentProps, "ref">'.ts(2741)
index.d.mts(8, 5): 'variant' is declared here.
```

### Expected

We should be able to render Icon without specifying `variant` prop, which should default to `mono`.

```tsx
<TokenMATIC className="size-4" />
```

---

Thank you!

**Comment by 0xa3k5** [comment]
hey thank you @junwen-k !

its a bit trickier than just simply defaulting to `mono` because not all of the icons has the `mono` variants, some icons only come with `branded`, for the majority of the icons that don't come with both variants, the `mono` variant should be the most common one.

I'll look into how to approach this; maybe we can default to whatever the icon has so the prop can be optional.

**Comment by junwen-k** [comment]
> hey thank you @junwen-k !
> 
> its a bit trickier than just simply defaulting to `mono` because not all of the icons has the `mono` variants, some icons only come with `branded`, for the majority of the icons that don't come with both variants, the `mono` variant should be the most common one.
> 
> I'll look into how to approach this; maybe we can default to whatever the icon has so the prop can be optional.

Thank you for the fast reply. Looks like my assumption was incorrect, I thought all icons always comes with a `mono` variant. That makes a lot of sense now!

Another potential solution would be to change the import path to indicate the type of the icon instead of controlling it using `variant` prop. (e.g, [Heroicons](https://heroicons.com/) uses this method).

```ts
import { TokenMATIC } from '@web3icons/react/mono' // mono indicates `mono` variant

import { TokenMATIC } from '@web3icons/react/branded' // branded indicates `branded` variant
```

Of course, this is a breaking changes and using this can omit the `variant` prop entirely.
