### ISSUE TITLE
the newest version @3.6.2 keeps on throwing typescript errors 

### ISSUE THREAD

**Issue by Ezejaemmanuel** [0xa3k5/web3icons#29]

**Comment by 0xa3k5** [comment]
I'm sorry but this is not helpful at all, can you share some information? I just tested with a fresh `create-next-app` and things are working fine.

what typescript error are you getting, your typescript version, your node version, your repo setup would be a good start. If you can link to your repo, even better.

**Comment by Ezejaemmanuel** [comment]
i was getting this error .....
Could not find a declaration file for module '@web3icons/react'. 'C:/Users/HP/development/web-development/javascript-node/blockchain-frontend/pump-like-new/node_modules/.pnpm/@web3icons+react@3.6.2_react@18.3.1_typescript@5.6.3/node_modules/@web3icons/react/dist/index.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/web3icons__react` if it exists or add a new declaration (.d.ts) file containing `declare module '@web3icons/react';`ts(7016)
⚠ Error (TS7016)  | 
Could not find a declaration file for module 
 . C:/Users/HP/development/web-development/javascript-node/blockchain-frontend/pump-like-new/node_modules/.pnpm/@web3icons+react@3.6.2_react@18.3.1_typescript@5.6.3/node_modules/@web3icons/react/dist/index.mjs implicitly has an 
 type.

**Comment by 0xa3k5** [comment]
yes, someone else reported the same issue; for some reason the new versino didn't include the typings. I'll fix

**Comment by Ezejaemmanuel** [comment]
Okay .... Thanks... I am really enjoying the package...... Keep up the good work... Hoping to be an open source(npm package) developer one day ..... Though at the moment still new to web development
