### ISSUE TITLE
Incorrect Token and Network Logos in Token and Network Tabs on UI

### ISSUE THREAD

**Issue by thesushilsharma** [0xa3k5/web3icons#30]
#### Token Tab:

- **Current Token**: Base (Incorrect Logo, It is Base Network's Logo)
  ![Base Network Logo](https://github.com/user-attachments/assets/041c3940-cc70-4db7-a792-2f69b934eb1d)

- **Token Address**: [0xd07379a755a8f11b57610154861d694b2a0f615a](https://basescan.org/address/0xd07379a755a8f11b57610154861d694b2a0f615a)

- **Real Name**: SwapBased Token

- **Real Token Logo**: 
  ![SwapBased Token Logo](https://github.com/user-attachments/assets/5dd21243-e9c5-4b56-9231-4e7a9dbd29d0)

- **Token Media Kit**: [SwapBased Token Media Kit](https://docs.swapbased.finance/informational/media-kit)

#### Network Tab:

- **Current Network Logo**: (Incorrect Logo - Beam Wallet's Logo, Should be Base Network)
  ![Beam Wallet Logo](https://github.com/user-attachments/assets/c8f32807-7c47-4cfb-99ae-9822787cd05e)

- **Base Network Logo Media Kit**: [Base Network Media Kit](https://github.com/base-org/brand-kit?tab=readme-ov-file#logos)

#### Action Needed:

1. Replace the incorrect Base Network logo in the **Token Tab** with the **SwapBased Token** logo.
2. Ensure the **real name** of the token is correctly updated to **SwapBased Token**.
3. Replace the incorrect **Beam Wallet** logo in the **Network Tab** with the correct **Base Network** logo from the [Base Network Media Kit](https://github.com/base-org/brand-kit?tab=readme-ov-file#logos).

**Comment by 0xa3k5** [comment]
thank you very much for this, I'll do the fix soon
