### ISSUE TITLE
Iconify Support

### ISSUE THREAD

**Issue by oritwoen** [0xa3k5/web3icons#35]
It would be great if there was an [`Iconify`](https://iconify.design/) package for these icons. This would allow them to be used in many libraries and frameworks, e.g.:

- https://github.com/nuxt/icon
- https://iconify.design/docs/icon-components/react

**Comment by 0xa3k5** [comment]
thank you, its already [supported](https://github.com/iconify/icon-sets/blob/c9b39a6667ac79293892743884d9547de01c855a/collections.md?plain=1#L1198)

**Comment by oritwoen** [comment]
Awesome! I don't know how I missed that 😅
