### ISSUE TITLE
Generic placeholder icon

### ISSUE THREAD

**Issue by YaroShkvorets** [0xa3k5/web3icons#42]
Would be great to have a placeholder icon (maybe more than one) that could be used for networks that don't have an icon in the library. 
Some kind of generic blockchain/network logo.

![image](https://github.com/user-attachments/assets/334e328c-66dc-4f13-ab58-2ce218a0da20)
![image](https://github.com/user-attachments/assets/7c93c859-8553-43d7-96fe-1d7d54a8e93d)

**Comment by 0xa3k5** [comment]
@YaroShkvorets if you are using `<NetworkIcon />` component, you can use the `fallback` prop to render any image if the component can't find a network with the passed props. 

```
<NetworkIcon network="new-network" fallback="/my-image.png" />
```

or you can pass any valid ReactNode to the fallback.

**Comment by YaroShkvorets** [comment]
Good to know, thanks
